[package]
name = "itp-stf-primitives"
version = "0.9.0"
authors = ["Integritee AG <hello@integritee.network>"]
edition = "2021"

[dependencies]
# crates.io
codec = { version = "3.0.0", default-features = false, features = ["derive"], package = "parity-scale-codec" }

# Substrate dependencies
sp-core = { default-features = false, features = ["full_crypto"], git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }

# local
itp-sgx-runtime-primitives = { default-features = false, path = "../sgx-runtime-primitives" }

[features]
default = ["std"]
std = [
    # crates.io
    "codec/std",
    # substrate
    "sp-core/std",
    "sp-runtime/std",
    "itp-sgx-runtime-primitives/std",
]
