[package]
name = "itp-stf-primitives"
version = "0.1.0"
edition = "2021"

[dependencies]
# crates.io
codec = { version = "3.0.0", default-features = false, features = ["derive"], package = "parity-scale-codec" }
derive_more = { version = "0.99.5" }
log = { version = "0.4", default-features = false }

# sgx deps
sgx_tstd = { branch = "master", features = ["untrusted_fs", "net", "backtrace"], git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }

# local crates
ita-sgx-runtime = { default-features = false, path = "../../app-libs/sgx-runtime" }
itp-sgx-externalities = { default-features = false, path = "../../core-primitives/substrate-sgx/externalities" }
itp-stf-interface = { default-features = false, path = "../../core-primitives/stf-interface" }
itp-storage = { default-features = false, path = "../../core-primitives/storage" }
itp-types = { default-features = false, path = "../../core-primitives/types" }
itp-utils = { default-features = false, path = "../../core-primitives/utils" }
sp-io = { default-features = false, features = ["disable_oom", "disable_panic_handler", "disable_allocator"], path = "../../core-primitives/substrate-sgx/sp-io" }


# Substrate dependencies
frame-support = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.29" }
frame-system = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.29" }
pallet-sudo = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.29" }
sp-application-crypto = { default-features = false, features = ["full_crypto"], git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.29" }
sp-core = { default-features = false, features = ["full_crypto"], git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.29" }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.29" }

# scs / integritee
my-node-runtime = { package = "integritee-node-runtime", optional = true, git = "https://github.com/integritee-network/integritee-node.git", branch = "master" }


[features]
default = ["std"]
sgx = [
    "sgx_tstd",
    "itp-sgx-externalities/sgx",
    "itp-utils/sgx",
    "sp-io/sgx",
]
std = [
    # crates.io
    "codec/std",
    "log/std",
    # local
    "ita-sgx-runtime/std",
    "itp-stf-interface/std",
    "itp-storage/std",
    "itp-types/std",
    "itp-utils/std",
    # substrate
    "sp-core/std",
    "sp-runtime/std",
    "pallet-sudo/std",
    "frame-system/std",
    "frame-support/std",
    "sp-application-crypto/std",
    # scs/integritee
    "my-node-runtime",
    "sp-io/std",
]
