[package]
name = "itp-api-client-types"
version = "0.9.0"
authors = ["Integritee AG <hello@integritee.network>"]
edition = "2021"

[dependencies]
# integritee-node
#my-node-runtime = { package = "integritee-node-runtime", optional = true, git = "https://github.com/integritee-network/integritee-node.git", branch = "sdk-v0.12.0-polkadot-v0.9.42" }
my-node-runtime = { package = "integritee-runtime", git = "https://github.com/integritee-network/parachain", branch = "sdk-v0.12.6-polkadot-v0.9.42", optional = true }
#ita-parentchain-interface = { default-features = false, path = "../../../app-libs/parentchain-interface" }
# scs
itp-types = { default-features = false, path = "../../types" }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
substrate-api-client = { default-features = false, features = ["sync-api"], git = "https://github.com/scs/substrate-api-client.git", branch = "polkadot-v0.9.42-tag-v0.14.0" }

[features]
default = ["std"]
std = [
    "itp-types/std",
    "substrate-api-client/std",
    "substrate-api-client/tungstenite-client",
    "sp-runtime/std",
    "my-node-runtime",
    #"ita-parentchain-interface/std",
]
