name: Publish Docker image for new teeracle & attesteer release

on:
  release:
    types:
      - published

jobs:
  main:
    name: Push Integritee Images to Dockerhub
    runs-on: [ self-hosted ]

    strategy:
      fail-fast: false
      matrix:
        include:
          - flavor_id: teeracle
          - flavor_id: attesteer

    steps:
      - uses: actions/checkout@v3

      - name: Download ${{ matrix.flavor_id }} from release
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: "tags/${{ github.event.release.tag_name }}"
          file: integritee-worker-${{ matrix.flavor_id }}-${{ github.event.release.tag_name }}.tar.gz
          target: "integritee-worker-${{ matrix.flavor_id }}.tar.gz"
          token: ${{ secrets.GITHUB_TOKEN }}
  

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Load Worker & Push
        env:
          DOCKER_BUILDKIT: 1
        run: |
            docker image load --input integritee-worker-${{ matrix.flavor_id }}.tar.gz
            docker images --all
            docker push integritee/${{ matrix.flavor_id }}:${{ github.event.release.tag_name }}
  
      - name: Delete images
        run: |
          if [[ "$(docker images -q integritee/${{ matrix.flavor_id }}:${{ github.event.release.tag_name }} 2> /dev/null)" != "" ]]; then
              docker image rmi --force integritee/${{ matrix.flavor_id }}:${{ github.event.release.tag_name }} 2>/dev/null
          fi
          docker images --all
